package org.GUI.menus;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import org.event.tools.Monitor;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.security.MessageDigest;
import java.util.Locale;

public class Menu {
    private JFrame frame;
    public JPanel panel1;
    private JButton CCButton;
    private JButton BankButton;
    private JButton LRUButton;
    private JButton OPTButton;
    Monitor monitor;

    public JPanel getHomePanel() {
        return this.panel1;
    }

    public Menu() {
        frame = new JFrame("菜单");
        frame.setContentPane(panel1);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
        monitor = new Monitor();
        CCButton.addActionListener(monitor);
        BankButton.addActionListener(monitor);
        OPTButton.addActionListener(monitor);
        LRUButton.addActionListener(monitor);
        LRUButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                frame.dispose();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("center:20px:noGrow,left:4dlu:noGrow,fill:100px:noGrow,left:5dlu:noGrow,fill:100px:noGrow,left:5dlu:noGrow,fill:100px:noGrow,left:4dlu:noGrow,fill:110px:noGrow,left:4dlu:noGrow,fill:100px:noGrow,left:4dlu:noGrow,fill:20px:noGrow", "center:20px:noGrow,top:4dlu:noGrow,center:200px:noGrow,top:5dlu:noGrow,center:85px:noGrow,top:4dlu:noGrow,center:50px:noGrow"));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        CellConstraints cc = new CellConstraints();
        panel1.add(panel2, cc.xyw(3, 3, 9, CellConstraints.FILL, CellConstraints.FILL));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Bodoni MT", Font.PLAIN, 28, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setText("<html>ComputerSystem<BR>ProcessAndStorageControlAlogirthm</BR></html>");
        panel2.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(360, 83), null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FormLayout("fill:20px:noGrow,left:4dlu:noGrow,fill:115px:noGrow,left:5dlu:noGrow,fill:110px:noGrow,left:5dlu:noGrow,fill:110px:noGrow,left:5dlu:noGrow,fill:115px:noGrow", "center:85px:noGrow"));
        panel1.add(panel3, cc.xywh(3, 5, 9, 2, CellConstraints.DEFAULT, CellConstraints.FILL));
        CCButton = new JButton();
        CCButton.setPreferredSize(new Dimension(106, 50));
        CCButton.setText("生产者消费者");
        panel3.add(CCButton, cc.xy(3, 1));
        BankButton = new JButton();
        BankButton.setMaximumSize(new Dimension(94, 50));
        BankButton.setMinimumSize(new Dimension(94, 50));
        BankButton.setPreferredSize(new Dimension(94, 50));
        BankButton.setText("银行家算法");
        panel3.add(BankButton, cc.xy(5, 1));
        LRUButton = new JButton();
        LRUButton.setPreferredSize(new Dimension(81, 50));
        LRUButton.setText("退出");
        panel3.add(LRUButton, cc.xy(9, 1));
        OPTButton = new JButton();
        OPTButton.setPreferredSize(new Dimension(106, 50));
        OPTButton.setText("调度算法综述");
        panel3.add(OPTButton, cc.xy(7, 1));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
