package org.GUI.Form;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import javafx.util.Pair;
import org.GUI.menus.ProducterAndConsumer;
import org.data.objects.Consumer;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

public class AddConsumerFrom {
    public JFrame frame;
    ProducterAndConsumer p;
    private JPanel panel1;
    private JTextField textField1;
    private JButton confirmButton;
    private JButton cancelButton;
    private JButton addItemButton;
    private JTable ItemTable;
    private JSpinner spinner1;
    private JButton 删除该行Button;
    DefaultTableModel tableModel;

    public JPanel getHomePanel() {
        return panel1;
    }


    void addConsumers2Data() {
        Consumer t = new Consumer();
        System.out.println("消费者名称：" + textField1.getText());
        t.setName(textField1.getText());
        int row = tableModel.getRowCount();
        ArrayList<Pair<String, Integer>> list = new ArrayList<>();
        for (int i = 0; i < row; i++) {
            System.out.println("消费品名称：" + (String) tableModel.getValueAt(i, 0)
                    + ",消费品数量：" + (String) tableModel.getValueAt(i, 1));
            t.getConsumeItems().add(new
                    Pair<String, Integer>((String) tableModel.getValueAt(i, 0)
                    , Integer.valueOf((String) tableModel.getValueAt(i, 1)))
            );
            list.add(new Pair<>((String) tableModel.getValueAt(i, 0)
                    , -Integer.valueOf((String) tableModel.getValueAt(i, 1))));
            System.out.println(t.getConsumeItems().get(0));
        }
        ProducterAndConsumer.getInstance().getObjects().put(textField1.getText(), list);
        t.run();
    }

    public AddConsumerFrom(ProducterAndConsumer p) {
        this.p = p;
        frame = new JFrame("生产者消费者模型");
        frame.setContentPane(this.panel1);
        frame.pack();
        frame.setLocationRelativeTo(null);

        tableModel = (DefaultTableModel) ItemTable.getModel();
        tableModel.addColumn("资源昵称");
        tableModel.addColumn("资源数量");

        confirmButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                addConsumers2Data();
            }
        });
        cancelButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                frame.dispose();
            }
        });
        addItemButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                tableModel.addRow(new Object[]{});
            }
        });
        删除该行Button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                tableModel.removeRow((int) spinner1.getValue());
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:20px:noGrow,left:4dlu:noGrow,fill:100px:noGrow,left:5dlu:noGrow,fill:200px:noGrow,left:5dlu:noGrow,fill:20px:noGrow", "center:20px:noGrow,top:4dlu:noGrow,center:53px:noGrow,top:5dlu:noGrow,center:50px:noGrow,top:4dlu:noGrow,center:50px:noGrow,top:4dlu:noGrow,center:50px:noGrow,top:5dlu:noGrow,center:50px:noGrow,top:5dlu:noGrow,center:50px:noGrow,top:4dlu:noGrow,center:20px:noGrow"));
        textField1 = new JTextField();
        CellConstraints cc = new CellConstraints();
        panel1.add(textField1, cc.xy(5, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label1 = new JLabel();
        label1.setText("消费者昵称：");
        panel1.add(label1, cc.xy(3, 3));
        final JLabel label2 = new JLabel();
        label2.setText("消费者消费资源：");
        panel1.add(label2, cc.xy(3, 5));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, cc.xywh(5, 5, 1, 7, CellConstraints.FILL, CellConstraints.FILL));
        ItemTable = new JTable();
        scrollPane1.setViewportView(ItemTable);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, cc.xyw(3, 13, 3, CellConstraints.DEFAULT, CellConstraints.FILL));
        confirmButton = new JButton();
        confirmButton.setText("确认");
        panel2.add(confirmButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cancelButton = new JButton();
        cancelButton.setText("取消");
        panel2.add(cancelButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        addItemButton = new JButton();
        addItemButton.setText("添加资源");
        panel1.add(addItemButton, cc.xy(3, 7));
        spinner1 = new JSpinner();
        panel1.add(spinner1, cc.xy(3, 9, CellConstraints.FILL, CellConstraints.DEFAULT));
        删除该行Button = new JButton();
        删除该行Button.setText("删除该行");
        panel1.add(删除该行Button, cc.xy(3, 11));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
