package org.GUI.menus;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class MLFQ {
    private JTabbedPane Queues;
    private JScrollPane runQueue;
    private JTable runTable;
    private JScrollPane readyqueue;
    private JTable readyTable;
    private JScrollPane waitQueue;
    private JTable waitTable;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        Queues = new JTabbedPane();
        panel1.add(Queues, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        runQueue = new JScrollPane();
        Queues.addTab("运行队列", runQueue);
        runTable = new JTable();
        runQueue.setViewportView(runTable);
        readyqueue = new JScrollPane();
        Queues.addTab("就绪队列", readyqueue);
        readyTable = new JTable();
        readyqueue.setViewportView(readyTable);
        waitQueue = new JScrollPane();
        Queues.addTab("等待队列", waitQueue);
        waitTable = new JTable();
        waitQueue.setViewportView(waitTable);
    }
}
